CREATE TABLE `bionime_Site` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `STAFF_COUNT` int NOT NULL DEFAULT '0',
  `STAFF_LIST` longtext,
  `LAST_UPDATE` timestamp,
  `CREATE_DATE` timestamp,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb4